### ISSUE TITLE
CI.JS - Tech-Overhauls

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/green-metrics-tool#445] opened 2023-08-31 09:40 UTC
## Tech-Overhauls
	-> Can we get to a lower amount of loops
	- displayStatsTable once called inside the function filterMeasurements and once inside? Why?
	- not reusing convertValue?
	- not reusing getRepoIcon? Or at least factor this out to make it only check and escape te url part once
	- in some places: for every run doing escapeString on the repo again?
	- api_string has no modifier? also some other variables have no const/let modifier and are global
	- document.querySelector('#ci-data') three times?
	- Use the non-biased (uncorrected) argument in .std()
	- But look athttps://mathjs.org/docs/reference/functions/std.html

**Comment by dan-mm** [comment] 2023-09-18 08:32
All is done and merged to main branch.

Waiting for website to be updated to do a last look over on live / with real data and make sure it all works as intended.

**Comment by ArneTR** [comment] 2023-09-18 10:07
Main updated on live

**Comment by dan-mm** [comment] 2023-09-18 11:06
looks good to me

**Closed by dan-mm** 2023-09-18 11:06 UTC
